package kg.enesai.toshok.enums

enum class Permission {
    ACCOUNT_VIEW,
    ACCOUNT_UPDATE_APPROVED,
    ACCOUNT_DELETE_APPROVED,
    ACCOUNT_APPROVE,
    USER_VIEW,
    USER_CREATE_ALL,
    USER_UPDATE_ALL,
    USER_DELETE_ALL,
    GIFT_VIEW,
    PAGINATION
}